/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TapeRouteImport } from './routes/tape'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as MugRouteImport } from './routes/mug'
import { Route as FittedSheetRouteImport } from './routes/fitted-sheet'
import { Route as IndexRouteImport } from './routes/index'

const TapeRoute = TapeRouteImport.update({
  id: '/tape',
  path: '/tape',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const MugRoute = MugRouteImport.update({
  id: '/mug',
  path: '/mug',
  getParentRoute: () => rootRouteImport,
} as any)
const FittedSheetRoute = FittedSheetRouteImport.update({
  id: '/fitted-sheet',
  path: '/fitted-sheet',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fitted-sheet': typeof FittedSheetRoute
  '/mug': typeof MugRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tape': typeof TapeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fitted-sheet': typeof FittedSheetRoute
  '/mug': typeof MugRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tape': typeof TapeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fitted-sheet': typeof FittedSheetRoute
  '/mug': typeof MugRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tape': typeof TapeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/fitted-sheet' | '/mug' | '/robots.txt' | '/sitemap.xml' | '/tape'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fitted-sheet' | '/mug' | '/robots.txt' | '/sitemap.xml' | '/tape'
  id:
    | '__root__'
    | '/'
    | '/fitted-sheet'
    | '/mug'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/tape'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FittedSheetRoute: typeof FittedSheetRoute
  MugRoute: typeof MugRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TapeRoute: typeof TapeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tape': {
      id: '/tape'
      path: '/tape'
      fullPath: '/tape'
      preLoaderRoute: typeof TapeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mug': {
      id: '/mug'
      path: '/mug'
      fullPath: '/mug'
      preLoaderRoute: typeof MugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fitted-sheet': {
      id: '/fitted-sheet'
      path: '/fitted-sheet'
      fullPath: '/fitted-sheet'
      preLoaderRoute: typeof FittedSheetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FittedSheetRoute: FittedSheetRoute,
  MugRoute: MugRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TapeRoute: TapeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
